title: Sovereign of Aethra Wiki
description: Official public encyclopedia and lore archive for Sovereign of Aethra.
baseurl: /sovereign-of-aethra-wiki
url: https://iron-bloom-studio.github.io
markdown: kramdown
permalink: pretty
